// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hncwcwbybkxqtmbgheqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuY3djd2J5Ymt4cXRtYmdoZXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NzYyMjEsImV4cCI6MjA5MDA1MjIyMX0.o_zpO1Us5jGgBikwpfgNfvDmGwiKrOAssIJdfPA9-Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});